{% set python_min = '3.10' %}
{% set name = "aggregate" %}
{% set version = "0.23.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aggregate-{{ version }}.tar.gz
  sha256: 5f365226abcfe185d82e5da4ed17c54cbc9ad3b37f6f3a8b00da9ef2a3748230

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61
    - wheel
    - pip
  run:
    - python >={{ python_min }}
    - ipython
    - cycler
    - ipykernel
    - jinja2
    - matplotlib-base >=3.5
    - numpy
    - pandas
    - psutil
    - scipy
    - sly
    - titlecase

test:
  imports:
    - aggregate
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  summary: "Tools for creating and working with aggregate probability distributions."
  home: https://github.com/mynl/aggregate
  license: BSD-3-Clause
  license_file: LICENSE
  doc_url: https://aggregate.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - mynl
